first commit
made changes to feedreader.js
current jasmine error:  3 specs, 2 failures
TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
-------------------------------------------------------------
added two 2 specs : 
one to check url in allFeeds 
second to check name in allFeeds